name: CI/CD Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: echo "npm software was installed"
      - name: Run tests
        run: echo "npm testing done"
      - name: Deploy
        run: echo "Deployed successfully!"
